config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :listings do
    resources :reservations
  end

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	has_many :reservations
	mount_uploaders :tours, TourUploader
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :listing

	def calculate_price

      price_per_night = self.listing.price
      duration = (self.check_out - self.check_in).to_i
      self.total_cost = price_per_night * duration
      self.save
      
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :listings
  has_many :reservations
  mount_uploader :image, ProfileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	def new
		@listing = Listing.new
	end

	def create

		@listing = Listing.new(listing_params)
		@listing.user_id = current_user.id

		if @listing.save
		  redirect_to @listing
		else
		  #puts "\n\n[LOG] #{user.errors.full_messages}\n\n"
		  redirect_to root_path, notice: "Invalid form filling!"
		end
	end

	def show
		@listing = Listing.find(params[:id])

	end

	def edit
		if current_user.id == Listing.find(params[:id]).user_id
			@listing = Listing.find(params[:id])
		else 
			redirect_to root_path, notice: "You have no authorization to visit that page!"
		end
	end

	def update
		@listing = Listing.find(params[:id])

		if @listing.update(listing_params)
			redirect_to @listing
		else
			render 'edit'
		end
	end

	def destroy
		Listing.find(params[:id]).destroy
		redirect_to root_path
	end

	private

		def listing_params
			params.require(:listing).permit(:address, :price, :content, {tours: []})
		end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def new
		@reservation = Reservation.new
		@listing = Listing.find(params[:listing_id])
	end

	def create

		@reservation = Reservation.new(reservation_params)
		@reservation.user_id = current_user.id
		@reservation.listing_id = params[:listing_id]

		@reservation.calculate_price
		
		if @reservation.save
		  @listing = Listing.find(params[:listing_id])	
		  redirect_to @listing
		else
		  #puts "\n\n[LOG] #{user.errors.full_messages}\n\n"
		  redirect_to root_path, notice: "Invalid form filling!"
		end
	end

	def show
		@reservation = Reservation.find(params[:id])
	end

	def edit
		if current_user.id == Reservation.find(params[:id]).user_id
			@reservation = Reservation.find(params[:id])
			@listing = Listing.find(params[:listing_id])
		else 
			redirect_to root_path, notice: "You have no authorization to visit that page!"
		end
	end

	def update
		@reservation = Reservation.find(params[:id])
		@reservation.calculate_price

		if @reservation.update(reservation_params)
			redirect_to Listing.find(params[:listing_id])
		else
			render 'edit'
		end
	end

	def destroy
		Reservation.find(params[:id]).destroy
		redirect_to Listing.find(params[:listing_id])
	end

	private

		def reservation_params
			params.require(:reservation).permit(:user_id, :listing_id, :check_in, :check_out)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		# @image = MiniMagick::Image.open(@user.image.to_s)
		# @image = @image.path #=> "/var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/magick20140921-75881-1yho3zc.jpg"
		# @image = @image.resize "300x300"
		# @image = @image.format "png"
		# @image = @image.write "output.png"
	end

	def edit
		if current_user.id == User.find(params[:id]).id
			@user = User.find(params[:id])
		else 
			redirect_to root_path, notice: "You have no authorization to visit that page!"
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		redirect_to root_path
	end

	private

		def user_params
			params.require(:user).permit(:email, :image)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairbnb Rails Srs Trial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign Out', sign_out_path, method: :delete %>
      <%= link_to "User Page", user_path(current_user.id) %>
  <% else %>
      <%= link_to 'Sign In', sign_in_path %>
  <% end %>

  <%= link_to 'View Listings', root_path %>

  <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/listings/edit.html.erb
<%= form_for @listing do |l| %>
  Address of Listing: <%= l.text_field :address %> <br />
  Price per Night: <%= l.number_field :price %> <br />
  About Listing: <%= l.text_field :content %> <br />
  Listing Pictures: <%= l.file_field :tours, multiple: true %>
  <%= l.submit %>
<% end %>

app/views/listings/index.html.erb
<h1>PairBnB</h1>

<h3>Here are the listings available:</h3>

<% Listing.all.each do |l| %>

	<%= link_to listing_path(l.id) do %>
	  <ul>
	  <li><%= l.address %> </li>
	  <li>Price per Night: <%= l.price %> </li>
	  <li>Host: <%= l.user.email %> </li>
	  </ul>
	<% end %>
<% end %>

app/views/listings/new.html.erb
<h3>New Listing</h3>

<%= form_for @listing do |l| %>
  Address of Listing: <%= l.text_field :address %> <br />
  Price per Night: <%= l.number_field :price %> <br />
  About Listing: <%= l.text_field :content %> <br />
  Listing Pictures: <%= l.file_field :tours, multiple: true %>
  <%= l.submit %>
<% end %>

app/views/listings/show.html.erb
<h3>Listing Details:</h3>

<p>
Listing ID: <%= @listing.id %> <br />
Listing Address: <%= @listing.address %> <br />
Price per Night: <%= @listing.price %>
</p>

<h4>Host:</h4>
<%= link_to user_path(@listing.user_id) do %>
  <%= @listing.user.email %>
<% end %>

<h4>About Listing:</h4>
<%= @listing.content %> <br />
  <% image_num = 0 %>
      <% while image_num <= @listing.tours.length - 1 %>      
        <img src="<%= @listing.tours[image_num].thumb %>">
        <% image_num += 1 %>
      <% end %>


<!-- If the logged in user is not the one who created the listing, they can only make reservations and alter their own reservations. If the logged in user is the one who created the listing, they can view the email of the user who made the reservation and also delete the reservation that was made by all users. -->

<% if signed_in? %>
  <% if current_user.id == @listing.user_id %>
	  <%= link_to "Edit listing", edit_listing_path %>
	  <%= link_to "Delete listing", listing_path(@listing.id), method: :delete, data: { confirm: "Are you sure to delete this listing?" } %>

	  <% Reservation.all.each do |r| %>
	    <% if r.listing_id == @listing.id   %>
	      <ul>
	  	    <li>Check in: <%= r.check_in %> </li>
	  	    <li>Check out: <%= r.check_out %> </li>
	  	    <li>User Email: <%= link_to user_path(r.user_id) do %>
  			  <%= r.user.email %> <% end %> </li>
	  	  </ul>
	      <%= link_to "Delete Reservation", listing_reservation_path(r.listing_id, r.id), method: :delete, data: { confirm: "Are you sure to delete this reservation?" } %>
	    <% end %>
	  <% end %>
	    
  <% else %>
    <%= link_to "Make a reservation", new_listing_reservation_path(@listing.id) %>

    <h4> Current Reservations Made: </h4>

    <% Reservation.all.each do |r| %>

	  <% if @listing.id == r.listing_id %>
	    <ul>
	    <li>Check in: <%= r.check_in %> </li>
	    <li>Check out: <%= r.check_out %> </li>
	    </ul>

	      <% if current_user.id == r.user_id %>
	        <%= link_to "Edit Reservation", edit_listing_reservation_path(r.listing_id, r.id) %>
	        <%= link_to "Delete Reservation", listing_reservation_path(r.listing_id, r.id), method: :delete, data: { confirm: "Are you sure to delete this reservation?" } %>
	      <% end %>

	  <% end %>
    <% end %>

  <% end %>
<% end %>

<!-- To Do: List the user's reservations out in front for better control of own reservations. -->

app/views/reservations/edit.html.erb
<p>
Listing ID: <%= @listing.id %> <br />
Listing Address: <%= @listing.address %> <br />
Price per Night: <%= @listing.price %>
</p>

<ul>
  <li>Current Check in: <%= @reservation.check_in %> </li>
  <li>Current Check out: <%= @reservation.check_out %> </li>
  <li>Current Total Price: <%= @reservation.total_cost %> </li>
</ul>

<%= form_for [@listing, @reservation] do |r| %>
  
  <label>New Check in </label>
    <input value="<%= @reservation.check_in %>" type="date" name="reservation[check_in]"><br />
  <label>New Check out </label>
    <input value="<%= @reservation.check_out %>" type="date" name="reservation[check_out]"><br />
  <%= r.submit %>

<% end %>

app/views/reservations/new.html.erb
<h3>New Reservation</h3>

<p>
Listing ID: <%= @listing.id %> <br />
Listing Address: <%= @listing.address %> <br />
Price per Night: <%= @listing.price %>
</p>

<%= form_for [@listing, @reservation] do |r| %>
  <label>Check in </label>
    <input type="date" name="reservation[check_in]"><br />
  <label>Check out </label>
    <input type="date" name="reservation[check_out]"><br />
  <%= r.submit %>
<% end %>

app/views/reservations/show.html.erb
<h3>Listing Details:</h3>

<p>
Listing ID: <%= @reservation.id %> <br />
Listing Address: <%= @reservation.listing.address %> <br />
Price per Night: <%= @reservation.listing.price %>
</p>

<h4>Host:</h4>
<%= link_to user_path(@listing.user_id) do %>
  <%= @listing.user.email %>
<% end %>

<h4>About Listing:</h4>
<%= @listing.content %> <br />


<!-- Only shows this if current user matches user show page id -->
<% if current_user.id == @listing.user_id %>
  <%= link_to "Edit listing", edit_listing_path %>
  <%= link_to "Delete listing", listing_path(@listing.id), method: :delete, data: { confirm: "Are you sure to delete this listing?" } %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.text_field :email %>

	<p>
      <%= f.file_field :image %>
    </p>
    
	<%= f.submit %>
<% end %>

app/views/users/login.html.erb
<% if !logged_in? %>
	<h1>Quodit!</h1>

	<p>Click here to look at today's questions!</p>
	<form method='get' action='/questions'>
  	  <input type=submit value="Look at Questions">
  	</form>

	<h2>Login here!</h2>
	<form method=get action=/sessions>
	<input type=text placeholder="Email" name="user[email]">
	<br />
	<input type=password placeholder="Password" name="user[password]">
	<br />
	<input type=submit value="Login">
	</form>

	<h2>Don't have an account? Create your account here!</h2>
	<form method=post action=/users>
	<input type=text placeholder="Email" name="user[email]">
	<br />
	<input id="emailcheck" type=text placeholder="Confirm Email" name="user[email]">
	<br />
	<input type=password placeholder="Password" name="user[password]">
	<br />
	<input id="pwcheck"type=password placeholder="Confirm Password" name="user[password]">
	<br />
	<input type=submit value="Sign Up">
	</form>

<!--How do I put out @notice?-->
	<p id="error"> <%= @notice %> </p>

<% else %>

	<p> Hi there, </p>
      <%= current_user.email %>
  	<p>What would you like to do today?</p>

  	<form method='get' action='/users/:id'>
  	  <input type=submit value="Go to User Page">
  	</form>

  	<form method='post' action='/logout'>
  	  <input type=submit value="Logout">
  	</form>

	<form method='get' action='/questions'>
  	  <input type=submit value="Look at Questions">
  	</form>

<% end %>

app/views/users/show.html.erb
<div id="profile">
  <%= image_tag @user.image.url %>
</div>


<%= @user.email %>

<% if @user.id == current_user.id %>
  <%= link_to "Edit profile", edit_user_path %>
  <%= link_to "Delete profile", user_path(@user.id), method: :delete, data: { confirm: "Are you sure to delete your account?" } %>
  <%= link_to 'Create Listing', new_listing_path %>

  <h3>Your Listings</h3>

    <% Listing.all.each do |l| %>

      <% if l.user_id == @user.id %>

	    <%= link_to listing_path(l.id) do %>

	        <ul>
	          <li><%= l.address %> </li>
	  		  <li>Price per Night: <%= l.price %> </li>
	  		  <li>Host: <%= l.user.email %> </li>
	  		</ul>

	    <% end %>
	  <% end %>
	<% end %>

<% else %>

  <h3>User Listings</h3>

    <% Listing.all.each do |l| %>

      <% if l.user_id == @user.id %>

	    <%= link_to listing_path(l.id) do %>

	        <ul>
	          <li><%= l.address %> </li>
	  		  <li>Price per Night: <%= l.price %> </li>
	  		  <li>Host: <%= l.user.email %> </li>
	  		</ul>

	    <% end %>
	  <% end %>
	<% end %>

<% end %>